### ISSUE TITLE
NameError: global name 'bin' is not defined

### ISSUE THREAD

**Issue by pzydog** [t0mm0/xbmc-urlresolver#4]
```
ERROR: Traceback (most recent call last):
    File "C:\Users\pzydog\AppData\Roaming\XBMC\addons\plugin.video.t0mm0.test\default.py", line 35, in ?
        stream_url = urlresolver.resolve(play)
    File "C:\Users\pzydog\AppData\Roaming\XBMC\addons\script.module.urlresolver\lib\urlresolver\__init__.py", line 66, in resolve
        return imp.get_media_url(web_url)
    File "C:\Users\pzydog\AppData\Roaming\XBMC\addons\script.module.urlresolver\lib\urlresolver\plugins\megavideo.py", line 39, in get_media_url
        return m.getLink()
    File "C:\Users\pzydog\AppData\Roaming\XBMC\addons\script.module.urlresolver\lib\urlresolver\plugins\lib\megavideo.py", line 33, in getLink
        except: self.decrypted = Megavideo_Decrypt(self.XML_FILE)
    File "C:\Users\pzydog\AppData\Roaming\XBMC\addons\script.module.urlresolver\lib\urlresolver\plugins\lib\megavideo.py", line 84, in __init__
        tobin = self.hex2bin(self.un)
    File "C:\Users\pzydog\AppData\Roaming\XBMC\addons\script.module.urlresolver\lib\urlresolver\plugins\lib\megavideo.py", line 121, in hex2bin
        string =  bin(int(val, 16))[2:].zfill(128)
    NameError: global name 'bin' is not defined
```

This happens when I try to play something from megavideo. The bin function has been added in python 2.6 but the Windows version of XBMC still uses python 2.4

**Comment by t0mm0** [comment]
thanks for this - yeah i spotted it yesterday when i tried it in dharma - that'll teach me for including a third party library without reading all the code ;-)

i'm thinking adding http://code.activestate.com/recipes/219300-format-integer-as-binary-string/#c6 to the top of the file will fix it? 

i'll do some testing...

**Comment by pzydog** [comment]
Looks interesting. If you want I could take a look at it tomorrow and create a patch if it works

**Comment by t0mm0** [comment]
yeah go for it - i won't get to it by then

thanks!

**Comment by pzydog** [comment]
OK I committed the fix to my open pull request

**Comment by t0mm0** [comment]
Thanks! I'll try and get it committed tonight if I get a chance to test.
On 17 Aug 2011 09:32, "pzydog" <
reply@reply.github.com>
wrote:

**Comment by t0mm0** [comment]
committed in c3090ba3d11ccea1dc3d327d7de0e8b4933fdda4 - thanks for the patches!
